version: '3.4'

services:
  server:
    build: .
    image: rediscrud
    network_mode: bridge
    ports:
      - '5000:5000'
    depends_on:
      - redis
    volumes:
      - .:/code
    links:
      - redis
  redis:
    image: redis/redis-stack-server
    ports:
      - '6379:6379'
    expose:
      - 6379
    network_mode: bridge
    

