version: '3.4'

services:
  server:
    image: rediscrud:latest
    environment:
      NODE_ENV: prod
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    expose:
      - "6379"

